export const generateRandomData = (sizeInBytes: number) => {
  const buffer = new ArrayBuffer(sizeInBytes);
  const view = new Uint8Array(buffer);

  for (let i = 0; i < sizeInBytes; i++) {
    view[i] = Math.floor(Math.random() * 256);
  }

  return buffer;
};

export const generateTextFile = (targetSize: number): Blob => {
  // Basic Lorem Ipsum paragraph for repetition
  const loremIpsum = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam euismod libero eget nunc vulputate, 
    quis volutpat nisl tincidunt. Sed vel semper magna, eget convallis mi. Suspendisse potenti. Nullam et dignissim nisi. 
    Vivamus eget justo vitae arcu molestie aliquam. Aliquam erat volutpat. Nam eget metus non mi finibus semper eget in purus. 
    Aenean pulvinar risus in ligula condimentum feugiat. Nulla facilisi. Cras convallis justo vel mattis placerat. 
    Donec varius malesuada interdum. Nulla facilisi. Nullam dignissim ipsum eu orci bibendum, at dignissim risus elementum.\n\n`;

  // Repeat the lorem ipsum text until we reach or exceed the target size
  let text = "";
  while (text.length < targetSize) {
    text += loremIpsum;
  }

  // Trim to the exact target size
  text = text.substring(0, targetSize);

  return new Blob([text], { type: "text/plain" });
};

export const generateJsonFile = (targetSize: number): Blob => {
  const baseObject: any = {
    id: "file-" + Math.random().toString(36).substring(2, 9),
    createdAt: new Date().toISOString(),
    type: "generated",
    size: targetSize,
    metadata: {
      generator: "ManyTools - Random File Creator",
      version: "1.0.0",
    },
    data: [],
  };

  let jsonString = JSON.stringify(baseObject, null, 2);
  let currentSize = jsonString.length;

  let entryId = 0;
  while (currentSize < targetSize) {
    const newEntry = {
      id: entryId++,
      timestamp: Date.now(),
      value: Math.random().toString(36).substring(2, 15),
      properties: {
        color: "#" + Math.floor(Math.random() * 16777215).toString(16),
        priority: Math.floor(Math.random() * 10),
        tags: Array(Math.floor(Math.random() * 5))
          .fill(0)
          .map(() => Math.random().toString(36).substring(2, 8)),
      },
    };

    baseObject.data.push(newEntry);

    // Recalculate size
    jsonString = JSON.stringify(baseObject, null, 2);
    currentSize = jsonString.length;
  }

  while (currentSize > targetSize && baseObject.data.length > 1) {
    baseObject.data.pop();
    jsonString = JSON.stringify(baseObject, null, 2);
    currentSize = jsonString.length;
  }

  const sizeDiff = targetSize - currentSize;
  if (sizeDiff > 0) {
    baseObject.comment = " ".repeat(sizeDiff);
    jsonString = JSON.stringify(baseObject, null, 2);
  }

  return new Blob([jsonString], { type: "application/json" });
};

export const generateZipFile = async (targetSize: number): Promise<Blob> => {
  const zipHeader = new Uint8Array([
    0x50, 0x4b, 0x03, 0x04, 0x14, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  ]);

  const remainingData = generateRandomData(targetSize - zipHeader.length);

  const combinedArray = new Uint8Array(targetSize);
  combinedArray.set(zipHeader);
  combinedArray.set(new Uint8Array(remainingData), zipHeader.length);

  return new Blob([combinedArray], { type: "application/zip" });
};

export const generateImageFile = (
  targetSize: number,
  mimeType: string,
  canvas: HTMLCanvasElement
): Promise<Blob> => {
  return new Promise((resolve) => {
    if (!canvas)
      return resolve(
        new Blob([generateRandomData(targetSize)], { type: mimeType })
      );

    const bytesPerPixel = mimeType === "image/jpeg" ? 0.25 : 0.5; // Rough approximation
    const totalPixels = targetSize / bytesPerPixel;

    // Find reasonable width/height with 4:3 aspect ratio
    let width = Math.sqrt(totalPixels * (4 / 3));
    let height = width * (3 / 4);

    width = Math.max(1, Math.round(width));
    height = Math.max(1, Math.round(height));

    canvas.width = width;
    canvas.height = height;

    const ctx = canvas.getContext("2d");
    if (!ctx)
      return resolve(
        new Blob([generateRandomData(targetSize)], { type: mimeType })
      );

    const createVisualContent = () => {
      const gradient = ctx.createLinearGradient(0, 0, width, height);
      gradient.addColorStop(0, getRandomColor());
      gradient.addColorStop(0.5, getRandomColor());
      gradient.addColorStop(1, getRandomColor());
      ctx.fillStyle = gradient;
      ctx.fillRect(0, 0, width, height);
      
      ctx.font = "bold 48px sans-serif";
      ctx.fillStyle = "rgba(255, 255, 255,1)";
      ctx.textAlign = "left";
      ctx.textBaseline = "top";
      ctx.fillText("Generated by ManyTools✅ v1.0.0", 50, 50);

      for (let i = 0; i < 20; i++) {
        ctx.beginPath();
        ctx.fillStyle = getRandomColor(0.7);

        const shapeType = Math.floor(Math.random() * 3);
        if (shapeType === 0) {
          const radius = Math.random() * width * 0.2;
          ctx.arc(
            Math.random() * width,
            Math.random() * height,
            radius,
            0,
            Math.PI * 2
          );
        } else if (shapeType === 1) {
          const rectWidth = Math.random() * width * 0.3;
          const rectHeight = Math.random() * height * 0.3;
          ctx.rect(
            Math.random() * width,
            Math.random() * height,
            rectWidth,
            rectHeight
          );
        } else {
          // Triangle
          const x1 = Math.random() * width;
          const y1 = Math.random() * height;
          const x2 = x1 + Math.random() * width * 0.3;
          const y2 = y1 + Math.random() * height * 0.3;
          const x3 = x1 + Math.random() * width * 0.3;
          const y3 = y1 - Math.random() * height * 0.3;

          ctx.moveTo(x1, y1);
          ctx.lineTo(x2, y2);
          ctx.lineTo(x3, y3);
          ctx.closePath();
        }

        ctx.fill();
      }
    };

    const getRandomColor = (alpha = 1) => {
      const r = Math.floor(Math.random() * 256);
      const g = Math.floor(Math.random() * 256);
      const b = Math.floor(Math.random() * 256);
      return `rgba(${r}, ${g}, ${b}, ${alpha})`;
    };

    createVisualContent();

    let quality = 0.7;
    let attempt = 0;
    const maxAttempts = 10;

    const generateBlob = () => {
      if (mimeType === "image/jpeg") {
        canvas.toBlob(
          (blob) => {
            if (!blob)
              return resolve(
                new Blob([generateRandomData(targetSize)], { type: mimeType })
              );

            const currentSize = blob.size;
            const ratio = targetSize / currentSize;

            if (Math.abs(1 - ratio) < 0.1 || attempt >= maxAttempts) {
              resolve(blob);
            } else {
              attempt++;
              quality = quality * Math.sqrt(ratio);
              quality = Math.max(0.1, Math.min(1.0, quality));
              generateBlob();
            }
          },
          mimeType,
          quality
        );
      } else {
        canvas.toBlob((blob) => {
          if (!blob)
            return resolve(
              new Blob([generateRandomData(targetSize)], { type: mimeType })
            );
          resolve(blob);
        }, mimeType);
      }
    };

    generateBlob();
  });
};
